accounts/urls.py
from django.urls import path
from .views import register_view,login_view,logout_view

app_name = "accounts"

urlpatterns = [
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('todo_app.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo_app/urls.py
from django.urls import path
from .views import (HomeView, TaskItemsListView, TaskItemCreateView, TaskItemArchivedListView,
                    TaskItemUpdateView, TaskItemDeleteView, TaskItemDetailView)

app_name = "todo_app"

urlpatterns = [
    path('', HomeView.as_view(), name="index"),
    path('tasks/', TaskItemsListView.as_view(), name="tasks"),
    path('tasks/archived/', TaskItemArchivedListView.as_view(), name="tasks_archived"),
    path('tasks/create/', TaskItemCreateView.as_view(), name="task_create"),
    path('tasks/edit/<int:pk>/', TaskItemUpdateView.as_view(), name="task_edit"),
    path('tasks/delete/<int:pk>/', TaskItemDeleteView.as_view(), name="task_delete"),
    path('tasks/detail/<int:pk>/', TaskItemDetailView.as_view(), name="task_detail"),

]

accounts/models.py
from django.db import models

# Create your models here.

todo_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.


class TodoItem(models.Model):
    title = models.CharField(max_length=128)
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    is_done = models.BooleanField("Completed", default=False)
    archive = models.BooleanField("archive", default=False)

    def get_absolute_url(self):
        # return reverse("model_detail", kwargs={"pk": self.pk})
        return "/"
    
    def __str__(self):
        return self.title

accounts/forms.py
from django import forms


class RegisterForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField()
    password_confirm = forms.CharField()
    email = forms.EmailField()

    def clean_password_confirm(self):
        cleaned_data = self.cleaned_data
        password1 = cleaned_data.get('password')
        password2 = cleaned_data.get('password_confirm')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                "your password must match with your password confirmation.",
                code='password_mismatch',
            )
        return password2


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

todo_app/forms.py
from django import forms
from .models import TodoItem

widget = {
    'title': forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter title of task'
    }),
    'description': forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Enter description of task'
    })
}


class TodoItemCreateForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['title', 'description']
        widgets = widget


class TodoItemUpdateForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ["title", "description", "is_done", "archive"]
        widgets = widget

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages
# Create your views here.


def register_view(request):
    context = {
        'reg': True
    }
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data.copy()
            clean_data.pop('password_confirm')
            get_user_model().objects.create_user(**clean_data)
            return redirect("/")
        else:
            context['form'] = form
    return render(request, 'accounts/register.html', context)


def login_view(request):
    context = {
        'login': True
    }
    next = request.GET.get('next', None)
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(**data)
            if user:
                login(request, user)
                if next is not None:
                    return redirect(next)
                return redirect("/")
            else:
                messages.error(
                    request, "username or password is incorrect", 'danger')
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    logout(request)
    return redirect("/")

todo_app/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, ListView, CreateView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TodoItem
from .forms import TodoItemCreateForm, TodoItemUpdateForm
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy


class HomeView(View):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        context = {
            'home': True
        }
        return render(request, self.template_name, context)


class TaskItemsListView(LoginRequiredMixin, ListView):
    model = TodoItem
    queryset = TodoItem.objects.all()
    template_name = "todo/todo_list.html"
    context_object_name = "tasks_list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = True
        return context

    def get_queryset(self):
        return TodoItem.objects.filter(user=self.request.user,archive=False)


class TaskItemArchivedListView(TaskItemsListView):
    def get_queryset(self):
        return TodoItem.objects.filter(user=self.request.user,archive=True)

class TaskItemCreateView(LoginRequiredMixin, CreateView):
    form_class = TodoItemCreateForm
    model = TodoItem
    template_name = "todo/task_create.html"

    def form_valid(self, form):
        task = form.save(commit=False)
        task.user = self.request.user
        task.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self) -> str:
        return reverse_lazy("todo_app:tasks")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create'] = True 
        return context


class TaskItemUpdateView(LoginRequiredMixin, UpdateView):
    form_class = TodoItemUpdateForm
    model = TodoItem
    pk_url_kwarg = "pk"
    template_name = "todo/task_create.html"
    success_url = reverse_lazy("todo_app:tasks")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if not obj.user == self.request.user:
            raise Http404
        return obj


class TaskItemDeleteView(LoginRequiredMixin, View):
    success_url = reverse_lazy("todo_app:tasks")

    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(
            TodoItem, pk=kwargs.get("pk"), user=request.user)
        obj.delete()
        return HttpResponseRedirect(self.success_url)


class TaskItemDetailView(LoginRequiredMixin, DetailView):
    model = TodoItem
    template_name = "todo/todo_detail.html"
    context_object_name = "task"
    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise Http404
        return obj

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <form class="form m-1" method="POST">
        {% csrf_token %}
        <div class="form-group m-1">
            <label for="username">Username:</label>
            <input type="text" class="form-control" name="username" id="username" required>
        </div>
        <div class="form-group m-1">
            <label for="password">Password:</label>

            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        
        <div class="form-group m-1 mt-3">
            <button class="form-control btn btn-dark" type="submit">
                login <i class="fa fa-enter fa-sm text-success"></i>
            </button>
        </div>
    </form>

</div>
{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
{% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %} 
              <div class="container text-dark m-5 alert alert-danger">
                   <strong>{{ error|escape }}</strong>
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %}
<div class="container m-5">
    <form class="form m-1" method="POST">
        {% csrf_token %}
        <div class="form-group m-1">
            <label for="username">Username:</label>
            <input type="text" class="form-control" name="username" id="username" required>
        </div>
        <div class="form-group m-1">
            <label for="email">Email:</label>
            <input type="email" class="form-control" id="email" name="email" required>
            {% if form.email.erorrs %}
                <small id="email_help" class="form-text text-muted">form.email.erorr.</small>
            {% endif %}
        </div>
        <div class="form-group m-1">
            <label for="password">Password:</label>

            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <div class="form-group m-1">
            <label for="password_confirm">Password confirm:</label>

            <input type="password" class="form-control" name="password_confirm" id="password_confirm" required>
        </div>
        <div class="form-group m-1 mt-3">
            <button class="form-control btn btn-dark" type="submit">
                Register <i class="fa fa-pen fa-sm text-success"></i>
            </button>
        </div>
    </form>

</div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Taskim - {% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet">

</head>


<body class="d-flex flex-column h-100">
    {% include 'navbar.html' %}
    {% block content %}{% endblock content %}
    <!-- Footer-->
    <footer class="footer mt-auto py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Taskim 2022</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
<header class="py-5 bg-image-full"
    style="background-image: url('{% static 'picture/header.jpg' %}'); background-position: center center;background-size: cover;">
    <div class="text-left m-5">
        <h1 class="text-white fs-3 fw-bolder"><span class="text-danger">T</span>askim</h1>
        <p class="text-secondary mb-0">A website for planning your <span class="text-success">tasks</span>.</p>
    </div>
</header>
<!-- Content section-->
<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2>What is Taskim?</h2>
                <p class="lead">Taskim is a website for manage your tasks.</p>
                <p class="mb-0">This project is still under development, so stay tuned...</p>
            </div>
        </div>
    </div>
</section>
<div class="py-5 bg-image-full" style="background-image: url('{% static 'picture/splash.jpg' %}');background-position: center center;background-size: cover;">
    <div style="height: 20rem"></div>
</div>
<!-- Content section-->
<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2>How To Use?</h2>
                <p class="lead">For using taskim you must login your profile</p>
                <p class="mb-0">If you dont have profile in Taskim. Don't worry because Taskim is free so you can register easly.</p>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand mb-2 mb-lg-0" href="/"><span class="text-success">task</span><span
            class="text-danger">im</span><i class="fa-solid fa-tasks fa-xs p-1"></i></a>
            <button class="navbar-toggler text-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
                aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if home %}active{% endif %}" aria-current="page" href="/"><i class="{% if home %}text-success{% endif %} fa fa-home"></i> Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link {% if tasks %}active{% endif %} dropdown-toggle" href="#" id="navbarTask" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="{% if tasks %}text-success{% endif %} fa fa-tasks"></i> Tasks
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarTask">
                      <li><a class="dropdown-item" href="{% url 'todo_app:tasks' %}"><i class="fa fa-check-square"></i> All Tasks</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'todo_app:tasks_archived' %}"><i class="fa fa-archive"></i> Archived</a></li>
                    </ul>
                  </li>
                
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if login %}active{% endif %}" href="{% url 'accounts:login' %}"><i class="{% if login %}text-success{% endif %} fa fa-user"></i> Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if reg %}active{% endif %}" href="{% url 'accounts:register' %}"><i class="{% if reg %}text-success{% endif %} fa fa-user-plus"></i> Register</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}"><i class="fa fa-sign"></i> Logout</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% if messages %}
<div class="container mt-2">
    {% for message in messages %}
    <div {% if message.tags %} class="m1- alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

templates/test.html
<div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card text-bg-dark mt-2" style="max-width: 18rem;">
                <div class="card-header">Header <i class="fa-solid fa-xs fa-x text-danger"></i></div>
                <div class="card-body">
                    <h5 class="card-title">Dark card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                        the card's content.</p>
                </div>
                <div class="card-footer text-center">
                    <button type="button" class="btn btn-dark btn-outline-light">
                        show <i class="fa-solid fa-book-open-reader"></i>
                    </button>

                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-bg-dark mt-2" style="max-width: 18rem;">
                <div class="card-header">Header <i class="text-success fa-xs fa-solid fa-check"></i></div>
                <div class="card-body">
                    <h5 class="card-title">Dark card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of
                        the card's content.</p>
                </div>
            </div>
        </div>
    </div>
</div>

templates/todo/task_create.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <form class="form m-1" method="POST">
        {% csrf_token %}
        {{form}}
        
        <div class="form-group m-1 mt-3">
            <button class="form-control btn btn-dark" type="submit">
                {% if create %}
                Create <i class="fa fa-plus	fa-sm text-success"></i>
                {% else %}
                update <i class="fa fa-edit	fa-sm text-success"></i>

                {% endif %}
            </button>
        </div>
    </form>

</div>
{% endblock content %}

templates/todo/todo_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col mt-2">
        <div class="card item-center mx-auto text-bg-dark m-5 p-2 h-100 w-50" >
            <div class="card-header"><h2>{{task.title}} <i
                    class="fa-solid fa-xs {% if task.is_done %}text-success fa-check {% else %} fa-x text-danger {% endif %}"></i><h2>
            </div>
            <div class="card-body d-flex flex-column">
                <h3 class="card-title">{{task.title}}</h5>
                <p class="card-text text-big">{{task.description}}</p>

                <a href="{% url 'todo_app:task_edit' task.pk %}" class="btn mt-auto btn-dark btn-outline-light">
                    update <i class="fa-solid fa-edit"></i>
                </a>
                <a href="{% url 'todo_app:task_delete' task.pk %}" class="btn mt-auto btn-dark btn-outline-danger">
                    delete <i class="fa-solid fa-trash"></i>
                </a>

            </div>
            <div class="card-footer text-mute">
                created at: {{task.created_date}}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/todo/todo_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="text-end m-2">

        <a href="{% url 'todo_app:task_create' %}">
            <button class="btn btn-dark text-end">
                <span class="badge bg-dark border border-light  text-success"><i class="fa fa-plus"></i></span> Add Task
            </button>
        </a>
    </div>

    <div class="row">
        {% for item in tasks_list %}
        <div class="col-lg-3 col-sm-6 col-md-4 mt-2">
            <div class="card text-bg-dark mt-2 p-2 h-100" style="max-width: 18rem;">
                <div class="card-header">{{item.title}} <i
                        class="fa-solid fa-xs {% if item.is_done %}text-success fa-check {% else %} fa-x text-danger {% endif %}"></i>
                </div>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{item.title}}</h5>
                    <p class="card-text">{{item.description|slice:50}}</p>

                    <a href="{% url 'todo_app:task_detail' item.pk %}" class="btn mt-auto btn-dark btn-outline-light">
                        show <i class="fa-solid fa-book-open-reader"></i>
                    </a>
                    <a href="{% url 'todo_app:task_delete' item.pk %}" class="btn mt-auto btn-dark btn-outline-danger">
                        delete <i class="fa-solid fa-trash"></i>
                    </a>

                </div>
                <div class="card-footer text-mute">
                    created at: {{item.created_date}}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}